"""PyInstaller entry point for the bundled agent/server executable.

A released, frozen build has no dev-mode ``.env`` pointing the database and
secret store at the OS user data directory (see agent/app/core/paths.py) —
that file is generated by ``agent/app/deployment/bootstrap_core.py``, which
only runs for the from-source setup. So this entry point applies the same
defaults itself, before importing anything that reads ``Settings`` at import
time, but only for variables the user's environment doesn't already set —
keeping user data outside the (replaceable) release folder.
"""

import os

os.environ.setdefault("WILLHABEN_APP_ENVIRONMENT", "production")


def _apply_default_paths() -> None:
    from agent.app.core.paths import default_database_path, default_secret_store_path

    os.environ.setdefault("WILLHABEN_DATABASE_PATH", str(default_database_path()))
    os.environ.setdefault("WILLHABEN_SECRET_STORE_PATH", str(default_secret_store_path()))


_apply_default_paths()

from agent.app.main import run  # noqa: E402

if __name__ == "__main__":
    run()
